/**
 * 
 */
package net.sf.ictalive.coordination.agents.diagram.oaw.dashboard;

import java.io.File;

import net.sf.ictalive.coordination.agents.diagram.oaw.util.AntUtils;
import net.sf.ictalive.coordination.agents.diagram.oaw.util.PathUtils;
import net.sf.ictalive.dashboard.PluggedInDashboardAction;
import net.sf.ictalive.runtime.dashboard.RuntimeDashboardState;

import org.apache.tools.ant.Project;

/**
 * Runtime dashboard action for starting the agent platform.
 * 
 * Invokes the build file generated by the Agent Model -> Derive -> Agents
 * action (provided by {@link GenerateAgentsDashboardAction}).
 * 
 * @author David Corsar
 * 
 */
public class StartAgentPlatformAction extends
		PluggedInDashboardAction<RuntimeDashboardState> {

	@Override
	public String dashboardActionId() {
		return RuntimeDashboardState.StartAgentPlatformId;
	}

	@Override
	public String getProblems(RuntimeDashboardState state) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void run(RuntimeDashboardState state) {
		File buildFile = new File(PathUtils.getAgentScapePath()
				+ File.separatorChar
				+ PathUtils.getRunAgentScapeBuildFileName());

		Project p = AntUtils.createAnyProject(buildFile);
		AntUtils.setAgentscapeBuildProperties(p);
		AntUtils.run(p);
		
		state.setAgentPlatformStatus(RuntimeDashboardState.STATUS_GREEN);
	}

}
