/**
 * 
 */
package net.sf.ictalive.coordination.wfvv.presentation;

import java.util.ArrayList;

import net.sf.ictalive.coordination.wfvv.EventModelContainer;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IResource;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Label;

/**
 * @author dcorsar
 *
 */
public class PreviousImportedAgentEventImporter extends
		EventSelectionImportPage {

	public PreviousImportedAgentEventImporter(){
		super(".event");
	}
	
	
	@Override
	public String getOptionText() {
		return "&Previously imported agent event files stored locally";
	}
	
	
	@Override
	protected String getTitleText() {
		return "Select the .event files generated by agents";
	}

	@Override
	public boolean isComplete() {
		return true;
	}


	@Override
	protected void addToControl(Composite control) {
		// TODO Auto-generated method stub
		
	}


	@Override
	public boolean importEvents(EventModelContainer to) {
		ArrayList<IResource> selectedResources = getSelectedFiles();
		for (IResource r : selectedResources){
			System.out.println("importing from " + r.getFullPath().toOSString());
		}
		return true;
	}

}
